-- =============================================================================
-- Rasi NovaTech SOC Platform - Production PostgreSQL / Supabase Migration
-- Purpose: Complete Normalized Schema for Real Windows Endpoint & Network Assets
-- Instructions: Paste this entire script into your Supabase SQL Editor and run it.
-- =============================================================================

-- Enable UUID extension if not already present
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. USERS & RBAC TABLE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) UNIQUE NOT NULL,
    email VARCHAR(128) UNIQUE NOT NULL,
    full_name VARCHAR(128) NOT NULL,
    hashed_password VARCHAR(256) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'SOC Analyst', -- 'Super Admin', 'SOC Admin', 'SOC Analyst', 'Viewer'
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

-- -----------------------------------------------------------------------------
-- 2. AGENTS TABLE (Managed Windows Endpoints Running RasiSOC-Agent.exe)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agents (
    agent_id VARCHAR(64) PRIMARY KEY, -- Stable UUID generated by EXE on install
    hostname VARCHAR(128) NOT NULL,
    computer_name VARCHAR(128),
    os_version VARCHAR(128),
    os_build VARCHAR(64),
    os_arch VARCHAR(32),
    current_ip VARCHAR(45) NOT NULL,
    mac_address VARCHAR(32) NOT NULL,
    agent_version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
    status VARCHAR(20) NOT NULL DEFAULT 'ONLINE', -- 'ONLINE', 'OFFLINE', 'WARNING'
    config_version INTEGER NOT NULL DEFAULT 1,
    auth_token VARCHAR(256) NOT NULL,
    cpu_model VARCHAR(128),
    cpu_cores INTEGER,
    ram_total_mb BIGINT,
    disk_total_gb BIGINT,
    uptime_sec BIGINT,
    first_seen TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    last_heartbeat TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_agents_hostname ON agents (hostname);
CREATE INDEX IF NOT EXISTS idx_agents_current_ip ON agents (current_ip);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents (status);
CREATE INDEX IF NOT EXISTS idx_agents_last_seen ON agents (last_seen);

-- -----------------------------------------------------------------------------
-- 3. ASSETS TABLE (All Discovered & Managed Network Devices & Endpoints)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assets (
    asset_id VARCHAR(64) PRIMARY KEY, -- e.g. AST-xxxx or Agent ID
    agent_id VARCHAR(64) REFERENCES agents(agent_id) ON DELETE SET NULL,
    hostname VARCHAR(128) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    mac_address VARCHAR(32) NOT NULL,
    category VARCHAR(32) NOT NULL DEFAULT 'Unknown', 
    -- 'Computer', 'Laptop', 'Server', 'Mobile', 'Router', 'Switch', 'Firewall', 'Printer', 'Camera', 'Access Point', 'IoT', 'Other', 'Unknown'
    manufacturer VARCHAR(64) DEFAULT 'Unknown',
    model VARCHAR(128) DEFAULT 'Unknown',
    os VARCHAR(128) DEFAULT 'Unknown',
    status VARCHAR(20) NOT NULL DEFAULT 'ONLINE', -- 'ONLINE', 'OFFLINE', 'UNKNOWN', 'WARNING'
    risk VARCHAR(20) NOT NULL DEFAULT 'None', -- 'Critical', 'High', 'Medium', 'Low', 'None'
    classification_confidence REAL DEFAULT 0.0, -- 0.0 to 1.0 confidence score
    subnet VARCHAR(45),
    vlan VARCHAR(32),
    network_vendor VARCHAR(64),
    is_managed BOOLEAN NOT NULL DEFAULT FALSE, -- True if running RasiSOC-Agent.exe
    discovery_method VARCHAR(64) DEFAULT 'Agent Probe', -- 'Agent Probe', 'ARP Sweep', 'ICMP', 'SNMP'
    first_seen TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    last_heartbeat TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_assets_ip ON assets (ip_address);
CREATE INDEX IF NOT EXISTS idx_assets_mac ON assets (mac_address);
CREATE INDEX IF NOT EXISTS idx_assets_hostname ON assets (hostname);
CREATE INDEX IF NOT EXISTS idx_assets_category ON assets (category);
CREATE INDEX IF NOT EXISTS idx_assets_status ON assets (status);
CREATE INDEX IF NOT EXISTS idx_assets_subnet ON assets (subnet);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets (last_seen);
CREATE INDEX IF NOT EXISTS idx_assets_created_at ON assets (created_at);

-- -----------------------------------------------------------------------------
-- 4. NETWORK INTERFACES TABLE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS network_interfaces (
    id SERIAL PRIMARY KEY,
    asset_id VARCHAR(64) NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    agent_id VARCHAR(64) REFERENCES agents(agent_id) ON DELETE CASCADE,
    interface_name VARCHAR(128) NOT NULL,
    ip_address VARCHAR(45),
    mac_address VARCHAR(32),
    gateway VARCHAR(45),
    subnet VARCHAR(45),
    vlan VARCHAR(32),
    is_up BOOLEAN DEFAULT TRUE,
    speed_mbps BIGINT,
    vendor VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_net_interfaces_asset ON network_interfaces (asset_id);
CREATE INDEX IF NOT EXISTS idx_net_interfaces_ip ON network_interfaces (ip_address);

-- -----------------------------------------------------------------------------
-- 5. ASSET DISCOVERY AUDIT LOGS (Raw Probe Results from Authorized Scans)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS asset_discovery (
    id SERIAL PRIMARY KEY,
    agent_id VARCHAR(64) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
    asset_id VARCHAR(64) REFERENCES assets(asset_id) ON DELETE SET NULL,
    target_subnet VARCHAR(45) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    mac_address VARCHAR(32),
    hostname VARCHAR(128),
    mac_vendor VARCHAR(64),
    probe_method VARCHAR(32) NOT NULL, -- 'ARP', 'ICMP', 'SNMP', 'TCP-SYN'
    classification_confidence REAL DEFAULT 0.0,
    discovered_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_discovery_agent ON asset_discovery (agent_id);
CREATE INDEX IF NOT EXISTS idx_discovery_ip ON asset_discovery (ip_address);
CREATE INDEX IF NOT EXISTS idx_discovery_time ON asset_discovery (discovered_at);

-- -----------------------------------------------------------------------------
-- 6. SOFTWARE INVENTORY TABLE (Real Installed Programs from Windows Registry)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS software_inventory (
    id SERIAL PRIMARY KEY,
    asset_id VARCHAR(64) NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    agent_id VARCHAR(64) REFERENCES agents(agent_id) ON DELETE CASCADE,
    name VARCHAR(256) NOT NULL,
    version VARCHAR(128),
    publisher VARCHAR(256),
    install_date VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_software_asset ON software_inventory (asset_id);
CREATE INDEX IF NOT EXISTS idx_software_name ON software_inventory (name);

-- -----------------------------------------------------------------------------
-- 7. SERVICE INVENTORY TABLE (Real Windows Background Services)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_inventory (
    id SERIAL PRIMARY KEY,
    asset_id VARCHAR(64) NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    agent_id VARCHAR(64) REFERENCES agents(agent_id) ON DELETE CASCADE,
    service_name VARCHAR(128) NOT NULL,
    display_name VARCHAR(256),
    status VARCHAR(32) NOT NULL, -- 'RUNNING', 'STOPPED', 'PAUSED'
    startup_type VARCHAR(32), -- 'AUTO_START', 'DEMAND_START', 'DISABLED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_services_asset ON service_inventory (asset_id);
CREATE INDEX IF NOT EXISTS idx_services_name ON service_inventory (service_name);

-- -----------------------------------------------------------------------------
-- 8. PORT INVENTORY TABLE (Real Local Listening TCP/UDP Ports & Associated PIDs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS port_inventory (
    id SERIAL PRIMARY KEY,
    asset_id VARCHAR(64) NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    agent_id VARCHAR(64) REFERENCES agents(agent_id) ON DELETE CASCADE,
    port INTEGER NOT NULL,
    protocol VARCHAR(10) NOT NULL DEFAULT 'TCP', -- 'TCP', 'UDP'
    service VARCHAR(64),
    state VARCHAR(20) DEFAULT 'LISTEN',
    pid INTEGER,
    process_name VARCHAR(128),
    last_detected TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_ports_asset ON port_inventory (asset_id);
CREATE INDEX IF NOT EXISTS idx_ports_port ON port_inventory (port);

-- -----------------------------------------------------------------------------
-- 9. AGENT HEARTBEATS TABLE (Lightweight Telemetry Log with Jitter)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_heartbeats (
    id SERIAL PRIMARY KEY,
    agent_id VARCHAR(64) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
    cpu_usage_pct REAL,
    ram_usage_pct REAL,
    disk_usage_pct REAL,
    uptime_sec BIGINT,
    payload_bytes INTEGER DEFAULT 0,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_heartbeats_agent ON agent_heartbeats (agent_id);
CREATE INDEX IF NOT EXISTS idx_heartbeats_time ON agent_heartbeats (timestamp);

-- -----------------------------------------------------------------------------
-- 10. DISCOVERY RANGES TABLE (Administrator-Configured Authorized CIDRs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS discovery_ranges (
    id SERIAL PRIMARY KEY,
    cidr VARCHAR(45) UNIQUE NOT NULL, -- e.g. '192.168.1.0/24'
    name VARCHAR(128) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    scan_interval_sec INTEGER NOT NULL DEFAULT 900, -- 15 mins default
    scan_jitter_sec INTEGER NOT NULL DEFAULT 30,    -- 30s randomized jitter
    max_packet_rate INTEGER NOT NULL DEFAULT 100,   -- Rate limiting
    snmp_community VARCHAR(64) DEFAULT 'public',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- -----------------------------------------------------------------------------
-- 11. AGENT CONFIGURATIONS TABLE (Versioned Global Discovery Configurations)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_configurations (
    version SERIAL PRIMARY KEY,
    config_json JSONB NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by VARCHAR(64) DEFAULT 'Super Admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- -----------------------------------------------------------------------------
-- 12. SECURITY ALERTS TABLE (Real Telemetry Ingested from Wazuh / OpenSearch)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS security_alerts (
    alert_id VARCHAR(64) PRIMARY KEY, -- e.g. 'ALT-1729001' or Wazuh Rule ID
    severity VARCHAR(20) NOT NULL, -- 'Critical', 'High', 'Medium', 'Low', 'Informational'
    asset_id VARCHAR(64) REFERENCES assets(asset_id) ON DELETE SET NULL,
    asset_hostname VARCHAR(128) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'Wazuh', -- 'Wazuh', 'OpenSearch', 'Sysmon'
    alert_type VARCHAR(128) NOT NULL,
    description TEXT NOT NULL,
    raw_payload JSONB,
    status VARCHAR(32) NOT NULL DEFAULT 'New', -- 'New', 'Investigating', 'Acknowledged', 'Resolved'
    assigned_analyst VARCHAR(64) DEFAULT 'Unassigned',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_alerts_severity ON security_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON security_alerts (status);
CREATE INDEX IF NOT EXISTS idx_alerts_asset ON security_alerts (asset_id);
CREATE INDEX IF NOT EXISTS idx_alerts_time ON security_alerts (created_at);

-- -----------------------------------------------------------------------------
-- 13. AUDIT LOGS TABLE (Immutable SOC Action & Configuration Changes)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    username VARCHAR(64) NOT NULL,
    action VARCHAR(128) NOT NULL,
    resource VARCHAR(128) NOT NULL,
    ip VARCHAR(45) DEFAULT '127.0.0.1',
    result VARCHAR(32) NOT NULL DEFAULT 'Success', -- 'Success', 'Failed', 'Denied'
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs (username);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_logs (created_at);

-- -----------------------------------------------------------------------------
-- 14. AGENT METRICS TABLE (Bandwidth Optimization & Telemetry Profiling)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_metrics (
    id SERIAL PRIMARY KEY,
    agent_id VARCHAR(64) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
    bytes_uploaded BIGINT DEFAULT 0,
    bytes_downloaded BIGINT DEFAULT 0,
    discovery_packets BIGINT DEFAULT 0,
    scan_duration_ms BIGINT DEFAULT 0,
    api_requests_count INTEGER DEFAULT 0,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_metrics_agent ON agent_metrics (agent_id);
CREATE INDEX IF NOT EXISTS idx_metrics_time ON agent_metrics (timestamp);

-- =============================================================================
-- SEED INITIAL SYSTEM DATA (NO FAKE ASSETS!)
-- Only baseline admin accounts and initial discovery configurations.
-- =============================================================================

-- 1. Default Super Admin (password: password123)
-- PBKDF2 HMAC SHA256 hashed password:
INSERT INTO users (username, email, full_name, hashed_password, role, is_active)
VALUES 
(
    'superadmin', 
    'superadmin@rasinovatech.soc', 
    'Chief Information Security Officer', 
    '0b151e285a8553ec406a445fe72776c59b6cb596e191a0c8cebc9ca62df7ec75', 
    'Super Admin', 
    TRUE
),
(
    'socadmin', 
    'admin@rasinovatech.soc', 
    'SOC Operations Lead', 
    '0b151e285a8553ec406a445fe72776c59b6cb596e191a0c8cebc9ca62df7ec75', 
    'SOC Admin', 
    TRUE
)
ON CONFLICT (username) DO NOTHING;

-- 2. Initial Authorized Discovery Range
INSERT INTO discovery_ranges (cidr, name, is_active, scan_interval_sec, scan_jitter_sec, max_packet_rate)
VALUES 
('192.168.1.0/24', 'Corporate Workstations Subnet', TRUE, 900, 30, 100),
('192.168.2.0/24', 'Engineering Laptops Subnet', TRUE, 900, 30, 100),
('10.0.10.0/24', 'Data Center Core Infrastructure', TRUE, 1800, 45, 50)
ON CONFLICT (cidr) DO NOTHING;

-- 3. Initial Active Agent Configuration Version 1
INSERT INTO agent_configurations (version, config_json, is_active, updated_by)
VALUES 
(
    1, 
    '{
        "version": 1,
        "heartbeat_interval_sec": 60,
        "heartbeat_jitter_sec": 15,
        "discovery_enabled": true,
        "authorized_cidrs": ["192.168.1.0/24", "192.168.2.0/24", "10.0.10.0/24"],
        "scan_interval_sec": 900,
        "scan_jitter_sec": 30,
        "max_packet_rate": 100,
        "enable_snmp": false,
        "snmp_community": "public",
        "wazuh_agent_monitoring": true
    }'::jsonb, 
    TRUE, 
    'System Initializer'
)
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- Migration Completed Successfully.
-- 0 Mock Assets Inserted. Ready for Real Agent Telemetry Ingestion.
-- =============================================================================
