from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Float, ForeignKey, Text, BigInteger, JSON
)
from sqlalchemy.orm import relationship
from app.database import Base

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), unique=True, index=True, nullable=False)
    email = Column(String(128), unique=True, index=True, nullable=False)
    full_name = Column(String(128), nullable=False)
    hashed_password = Column(String(256), nullable=False)
    role = Column(String(32), default="SOC Analyst", nullable=False) # 'Super Admin', 'SOC Admin', 'SOC Analyst', 'Viewer'
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class Agent(Base):
    __tablename__ = "agents"
    
    agent_id = Column(String(64), primary_key=True, index=True) # Stable UUID generated by EXE
    hostname = Column(String(128), index=True, nullable=False)
    computer_name = Column(String(128))
    os_version = Column(String(128))
    os_build = Column(String(64))
    os_arch = Column(String(32))
    current_ip = Column(String(45), index=True, nullable=False)
    mac_address = Column(String(32), nullable=False)
    agent_version = Column(String(32), default="1.0.0", nullable=False)
    status = Column(String(20), default="ONLINE", index=True, nullable=False) # ONLINE, OFFLINE, WARNING
    config_version = Column(Integer, default=1, nullable=False)
    auth_token = Column(String(256), nullable=False)
    cpu_model = Column(String(128))
    cpu_cores = Column(Integer)
    ram_total_mb = Column(BigInteger)
    disk_total_gb = Column(BigInteger)
    uptime_sec = Column(BigInteger)
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime, default=datetime.utcnow, index=True)
    last_heartbeat = Column(DateTime, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    heartbeats = relationship("AgentHeartbeat", back_populates="agent", cascade="all, delete-orphan")
    assets = relationship("Asset", back_populates="agent")

class Asset(Base):
    __tablename__ = "assets"
    
    asset_id = Column(String(64), primary_key=True, index=True)
    agent_id = Column(String(64), ForeignKey("agents.agent_id", ondelete="SET NULL"), nullable=True, index=True)
    hostname = Column(String(128), index=True, nullable=False)
    ip_address = Column(String(45), index=True, nullable=False)
    mac_address = Column(String(32), index=True, nullable=False)
    category = Column(String(32), index=True, default="Unknown", nullable=False)
    # Categories: Computer, Laptop, Server, Mobile, Router, Switch, Firewall, Printer, Camera, Access Point, IoT, Other, Unknown
    manufacturer = Column(String(64), default="Unknown")
    model = Column(String(128), default="Unknown")
    os = Column(String(128), default="Unknown")
    status = Column(String(20), default="ONLINE", index=True, nullable=False) # ONLINE, OFFLINE, UNKNOWN, WARNING
    risk = Column(String(20), default="None", index=True, nullable=False) # Critical, High, Medium, Low, None
    classification_confidence = Column(Float, default=0.0)
    subnet = Column(String(45), index=True)
    vlan = Column(String(32))
    network_vendor = Column(String(64))
    is_managed = Column(Boolean, default=False) # True if running RasiSOC-Agent.exe
    discovery_method = Column(String(64), default="Agent Probe")
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime, default=datetime.utcnow, index=True)
    last_heartbeat = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    agent = relationship("Agent", back_populates="assets")
    interfaces = relationship("NetworkInterface", back_populates="asset", cascade="all, delete-orphan")
    software = relationship("SoftwareInventory", back_populates="asset", cascade="all, delete-orphan")
    services = relationship("ServiceInventory", back_populates="asset", cascade="all, delete-orphan")
    ports = relationship("PortInventory", back_populates="asset", cascade="all, delete-orphan")
    alerts = relationship("SecurityAlert", back_populates="asset", cascade="all, delete-orphan")

class NetworkInterface(Base):
    __tablename__ = "network_interfaces"
    
    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="CASCADE"), nullable=False, index=True)
    agent_id = Column(String(64), nullable=True)
    interface_name = Column(String(128), nullable=False)
    ip_address = Column(String(45), index=True)
    mac_address = Column(String(32))
    gateway = Column(String(45))
    subnet = Column(String(45))
    vlan = Column(String(32))
    is_up = Column(Boolean, default=True)
    speed_mbps = Column(BigInteger)
    vendor = Column(String(64))
    created_at = Column(DateTime, default=datetime.utcnow)

    asset = relationship("Asset", back_populates="interfaces")

class AssetDiscovery(Base):
    __tablename__ = "asset_discovery"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String(64), ForeignKey("agents.agent_id", ondelete="CASCADE"), nullable=False, index=True)
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="SET NULL"), nullable=True)
    target_subnet = Column(String(45), nullable=False)
    ip_address = Column(String(45), index=True, nullable=False)
    mac_address = Column(String(32))
    hostname = Column(String(128))
    mac_vendor = Column(String(64))
    probe_method = Column(String(32), nullable=False) # 'ARP', 'ICMP', 'SNMP'
    classification_confidence = Column(Float, default=0.0)
    discovered_at = Column(DateTime, default=datetime.utcnow, index=True)

class SoftwareInventory(Base):
    __tablename__ = "software_inventory"
    
    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="CASCADE"), nullable=False, index=True)
    agent_id = Column(String(64), nullable=True)
    name = Column(String(256), index=True, nullable=False)
    version = Column(String(128))
    publisher = Column(String(256))
    install_date = Column(String(64))
    created_at = Column(DateTime, default=datetime.utcnow)

    asset = relationship("Asset", back_populates="software")

class ServiceInventory(Base):
    __tablename__ = "service_inventory"
    
    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="CASCADE"), nullable=False, index=True)
    agent_id = Column(String(64), nullable=True)
    service_name = Column(String(128), index=True, nullable=False)
    display_name = Column(String(256))
    status = Column(String(32), nullable=False) # 'RUNNING', 'STOPPED'
    startup_type = Column(String(32)) # 'AUTO_START', 'DEMAND_START', 'DISABLED'
    created_at = Column(DateTime, default=datetime.utcnow)

    asset = relationship("Asset", back_populates="services")

class PortInventory(Base):
    __tablename__ = "port_inventory"
    
    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="CASCADE"), nullable=False, index=True)
    agent_id = Column(String(64), nullable=True)
    port = Column(Integer, index=True, nullable=False)
    protocol = Column(String(10), default="TCP", nullable=False)
    service = Column(String(64))
    state = Column(String(20), default="LISTEN")
    pid = Column(Integer)
    process_name = Column(String(128))
    last_detected = Column(DateTime, default=datetime.utcnow)

    asset = relationship("Asset", back_populates="ports")

class AgentHeartbeat(Base):
    __tablename__ = "agent_heartbeats"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String(64), ForeignKey("agents.agent_id", ondelete="CASCADE"), nullable=False, index=True)
    cpu_usage_pct = Column(Float)
    ram_usage_pct = Column(Float)
    disk_usage_pct = Column(Float)
    uptime_sec = Column(BigInteger)
    payload_bytes = Column(Integer, default=0)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    agent = relationship("Agent", back_populates="heartbeats")

class DiscoveryRange(Base):
    __tablename__ = "discovery_ranges"
    
    id = Column(Integer, primary_key=True, index=True)
    cidr = Column(String(45), unique=True, index=True, nullable=False)
    name = Column(String(128), nullable=False)
    is_active = Column(Boolean, default=True)
    scan_interval_sec = Column(Integer, default=900)
    scan_jitter_sec = Column(Integer, default=30)
    max_packet_rate = Column(Integer, default=100)
    snmp_community = Column(String(64), default="public")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class AgentConfiguration(Base):
    __tablename__ = "agent_configurations"
    
    version = Column(Integer, primary_key=True, index=True)
    config_json = Column(JSON, nullable=False)
    is_active = Column(Boolean, default=True)
    updated_by = Column(String(64), default="Super Admin")
    created_at = Column(DateTime, default=datetime.utcnow)

class SecurityAlert(Base):
    __tablename__ = "security_alerts"
    
    alert_id = Column(String(64), primary_key=True, index=True)
    severity = Column(String(20), index=True, nullable=False) # 'Critical', 'High', 'Medium', 'Low', 'Informational'
    asset_id = Column(String(64), ForeignKey("assets.asset_id", ondelete="SET NULL"), nullable=True, index=True)
    asset_hostname = Column(String(128), nullable=False)
    source = Column(String(32), default="Wazuh", nullable=False)
    alert_type = Column(String(128), nullable=False)
    description = Column(Text, nullable=False)
    raw_payload = Column(JSON)
    status = Column(String(32), default="New", index=True, nullable=False) # 'New', 'Investigating', 'Acknowledged', 'Resolved'
    assigned_analyst = Column(String(64), default="Unassigned")
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    asset = relationship("Asset", back_populates="alerts")

class AuditLog(Base):
    __tablename__ = "audit_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    username = Column(String(64), index=True, nullable=False)
    action = Column(String(128), index=True, nullable=False)
    resource = Column(String(128), nullable=False)
    ip = Column(String(45), default="127.0.0.1")
    result = Column(String(32), default="Success", nullable=False) # 'Success', 'Failed', 'Denied'
    details = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

class AgentMetric(Base):
    __tablename__ = "agent_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String(64), ForeignKey("agents.agent_id", ondelete="CASCADE"), nullable=False, index=True)
    bytes_uploaded = Column(BigInteger, default=0)
    bytes_downloaded = Column(BigInteger, default=0)
    discovery_packets = Column(BigInteger, default=0)
    scan_duration_ms = Column(BigInteger, default=0)
    api_requests_count = Column(Integer, default=0)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
